import {
  BodyPositionEnum,
  Exercise,
  ExerciseTypeEnum,
  JointComplexityEnum,
  LoadTypeEnum,
  LocationEnum,
  MuscleGroupEnum,
  UniLateralTypeEnum,
  WeightSystemEnum
} from 'coaching-shared';

export const LIST_OF_EXERCISES: Exercise[] = [
  {
    name: 'Bench Press',
    muscleGroup: MuscleGroupEnum.CHEST,
    loadType: LoadTypeEnum.BARBELL,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Squat',
    muscleGroup: MuscleGroupEnum.LEGS,
    loadType: LoadTypeEnum.BARBELL,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Deadlift',
    muscleGroup: MuscleGroupEnum.BACK,
    loadType: LoadTypeEnum.BARBELL,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Pull-Up',
    muscleGroup: MuscleGroupEnum.BACK,
    loadType: LoadTypeEnum.BODY_WEIGHT,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Shoulder Press',
    muscleGroup: MuscleGroupEnum.SHOULDERS,
    loadType: LoadTypeEnum.DUMBBELL,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Bicep Curl',
    muscleGroup: MuscleGroupEnum.ARMS,
    loadType: LoadTypeEnum.DUMBBELL,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.ISOLATION,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Skull Crusher',
    muscleGroup: MuscleGroupEnum.ARMS,
    loadType: LoadTypeEnum.DUMBBELL,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.ISOLATION,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Lunge',
    muscleGroup: MuscleGroupEnum.LEGS,
    loadType: LoadTypeEnum.BODY_WEIGHT,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Plank',
    muscleGroup: MuscleGroupEnum.CORE,
    loadType: LoadTypeEnum.BODY_WEIGHT,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.ISOLATION,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: MuscleGroupEnum.BACK,
    loadType: LoadTypeEnum.MACHINE,
    location: LocationEnum.GYM,
    exerciseType: ExerciseTypeEnum.BASIC,
    link: 'https://www.youtube.com/shorts/FVZx9lfnYOM',
    weightSystem: WeightSystemEnum.KG,
    bodyPosition: BodyPositionEnum.LYING,
    unilateralType: UniLateralTypeEnum.UNILATERAL,
    jointComplexity: JointComplexityEnum.COMPOUND,
  },
];
