export enum BodyPositionEnum {
  STANDING = 'STANDING',
  SEATED = 'SEATED',
  LYING = 'LYING',
  KNEELING = 'KNEELING',
  HALF_KNEELING = 'HALF_KNEELING',
  QUADRUPED = 'QUADRUPED',
  SPLIT_STANCE = 'SPLIT_STANCE'
}
