export enum Equipment {
  BODY_WEIGHT = "BODY_WEIGHT",
  BAR = "BAR",
  DUMBBELLS = "DUMBBELLS",
  MACHINE = "MACHINE",
  RESISTANCE_BANDS = "RESISTANCE_BANDS",
  TRX = "TRX",
  KETTLEBELL = "KETTLEBELL",
}
