export enum LoadTypeEnum {
  BODY_WEIGHT = "BODY_WEIGHT",
  MOBILITY = 'MOBILITY',
  DUMBBELL = 'DUMBBELL',
  BARBELL = 'BARBELL',
  KETTLEBELL = "KETTLEBELL",
  MEDBALL = 'MEDBALL',
  BAND = 'BAND',
  MINI_BAND = 'MINI_BAND',
  TRX = 'TRX',
  BOSU = 'BOSU',
  YOGA_BALL = 'YOGA_BALL',
  MACHINE = 'MACHINE',
  CABLE = 'CABLE'
}
